# Generated by Django 2.2.13 on 2020-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='type',
            field=models.CharField(blank=True, choices=[('PACIENTE', 'PACIENTE'), ('MEDICO', 'MEDICO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], max_length=200, null=True),
        ),
    ]
