# Generated by Django 2.2.13 on 2020-09-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_medicamentocovid_medicamentoinyectable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicamentoCovid',
        ),
        migrations.DeleteModel(
            name='MedicamentoInyectable',
        ),
    ]
