# Generated by Django 2.2.13 on 2020-09-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200912_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
