# Generated by Django 2.2.13 on 2020-09-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_paciente_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cedula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
