# Generated by Django 2.2.13 on 2020-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200913_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
