# Generated by Django 2.2.13 on 2020-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_cita_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='sala',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
